-- Insertar las 98 preguntas del test CHASIDE
BEGIN;

INSERT INTO pregunta (numero, texto, categoria, dimension, test_id)
SELECT q.numero, q.texto, q.categoria, q.dimension, (SELECT id FROM test WHERE nombre='CHASIDE' LIMIT 1)
FROM (VALUES
  (1,  '¿Aceptaría trabajar escribiendo artículos en la sección económica de un diario?', 'C', 'INTERES'),
  (2,  '¿Se ofrecería para organizar la despedida de soltero/a de uno/a de uno de sus amigos/amigas?', 'C', 'APTITUD'),
  (3,  '¿Le gustaría dirigir un proyecto de urbanización en su ciudad?', 'A', 'INTERES'),
  (4,  '¿A una frustración siempre opone un pensamiento positivo?', 'S', 'APTITUD'),
  (5,  '¿Se dedicaría a socorrer personas accidentadas o atacadas por asaltantes?', 'D', 'INTERES'),
  (6,  '¿Cuando era niño/a, le interesaba saber cómo estaban construidos los juguetes?', 'I', 'INTERES'),
  (7,  '¿Le interesan más los misterios de la Naturaleza que los secretos de la tecnología?', 'E', 'APTITUD'),
  (8,  '¿Escucha atentamente los problemas planteados por sus amigos/as?', 'S', 'INTERES'),
  (9,  '¿Se ofrecería para explicar algo a alguien?', 'H', 'INTERES'),
  (10, '¿Es exigente y crítico con su trabajo?', 'I', 'APTITUD'),
  (11, '¿Le atrae armar puzzles o rompecabezas?', 'A', 'INTERES'),
  (12, '¿Puede establecer la diferencia conceptual entre microeconomía y macroeconomía?', 'C', 'INTERES'),
  (13, '¿Usar un uniforme lo/a haría sentirse distinto/a e importante?', 'D', 'APTITUD'),
  (14, '¿Participaría, como profesional, en un espectáculo de acrobacia aérea?', 'D', 'INTERES'),
  (15, '¿Organiza su dinero de manera que siempre alcance hasta volver a cobrar?', 'C', 'APTITUD'),
  (16, '¿Convence fácilmente a otras personas sobre la validez de sus argumentos?', 'S', 'INTERES'),
  (17, '¿Se encuentra informado/a sobre los nuevos descubrimientos sobre la Teoría del Big-Bang?', 'E', 'INTERES'),
  (18, '¿Ante una situación de emergencia, actúa rápidamente?', 'D', 'APTITUD'),
  (19, '¿Cuando tiene que resolver un problema matemático, es perseverante hasta encontrar la solución?', 'I', 'INTERES'),
  (20, '¿Si fuera convocado/a para planificar, organizar y/o dirigir un campo de deportes, aceptaría?', 'C', 'INTERES'),
  (21, '¿Es Ud. él/la que pone un toque de alegría en las fiestas familiares?', 'A', 'INTERES'),
  (22, '¿Cree que los detalles son tan importantes como el todo?', 'A', 'APTITUD'),
  (23, '¿Cree que los detalles son tan importantes como el todo?', 'A', 'APTITUD'),
  (24, '¿Le gustaría participar en el mantenimiento del orden ante grandes conflictos sociales o catástrofes?', 'D', NULL),
  (25, '¿Pasaría varias horas leyendo un libro de su interés?', 'H', NULL),
  (26, '¿Planifica cuidadosamente sus trabajos antes de iniciarlos?', 'I', NULL),
  (27, '¿Mantiene una relación casi personal con su computadora?', 'I', NULL),
  (28, '¿Disfruta modelando en arcilla?', 'A', NULL),
  (29, '¿Ayuda habitualmente a los no videntes a cruzar la calle?', 'S', NULL),
  (30, '¿Considera importante que, desde la escuela primaria, se fomente la actitud crítica y la participación activa?', 'H', NULL),
  (31, '¿Acepta que las mujeres formen parte de las Fuerzas Armadas, bajo las mismas normas que los hombres?', 'D', NULL),
  (32, '¿Le gustaría crear nuevas técnicas para descubrir las patologías de algunas enfermedades, usando un microscopio?', 'E', NULL),
  (33, '¿Participaría en una campaña de prevención de la enfermedad de Chagas?', 'S', NULL),
  (34, '¿Le interesa los temas relacionados con el pasado y con la evolución del hombre?', 'A', NULL),
  (35, '¿Se incluiría en un proyecto de investigación de los movimientos sísmicos y sus consecuencias?', 'E', NULL),
  (36, '¿Dedica algunas horas de la semana a la realización de actividad física?', 'A', NULL),
  (37, '¿Le interesan las actividades de mucha acción y de reacción rápida en situaciones imprevistas o de peligro?', 'D', NULL),
  (38, '¿Se ofrecería para colaborar como voluntario/a en los gabinetes especiales de la NASA?', 'I', NULL),
  (39, '¿Le gusta más el trabajo manual que el intelectual?', 'A', NULL),
  (40, '¿Estaría dispuesto/a a renunciar a un momento placentero para prestar su servicio como profesional?', 'S', NULL),
  (41, '¿Participaría de un trabajo de investigación sobre la violencia social?', 'H', NULL),
  (42, '¿Le gustaría trabajar en un laboratorio, mientras estudia?', 'E', NULL),
  (43, '¿Arriesgaría su vida para salvar la de un desconocido?', 'D', NULL),
  (44, '¿Le agradaría hacer un curso de primeros auxilios?', 'S', 'INTERES'),
  (45, '¿Toleraría empezar tantas veces como fuera necesario hasta obtener un logro deseado?', 'A', 'INTERES'),
  (46, '¿Distribuye los horarios adecuadamente para poder cumplir con lo planeado?', 'C', 'APTITUD'),
  (47, '¿Haría un curso para aprender a fabricar las piezas de máquinas o aparatos?', 'I', 'INTERES'),
  (48, '¿Elegiría una profesión que lo/a obligara a estar alejado de su familia por algún tiempo?', 'D', 'INTERES'),
  (49, '¿Se radicaría en una zona agrícola‑ganadera?', 'E', 'INTERES'),
  (50, '¿Cuando está trabajando en grupo, le entusiasma aportar ideas?', 'A', 'INTERES'),
  (51, '¿Le resulta fácil coordinar un grupo de trabajo?', 'C', 'APTITUD'),
  (52, '¿Le resultan interesantes las Ciencias Biológicas?', 'S', 'INTERES'),
  (53, '¿Si una empresa importante solicita un profesional para Gerente de Comercialización, le gustaría desempeñar esta función?', 'C', 'INTERES'),
  (54, '¿Se incluiría en un proyecto nacional de desarrollo de la principal fuente de recursos de su provincia?', 'I', 'INTERES'),
  (55, '¿Siente interés por descubrir cuáles son las causas que determinan ciertos fenómenos, aunque no altere su vida?', 'E', 'APTITUD'),
  (56, '¿Descubrió algún filósofo o escritor que haya expresado las mismas ideas de Ud. con anticipación?', 'H', 'INTERES'),
  (57, '¿Desearía que le regalen algún instrumento musical?', 'A', 'INTERES'),
  (58, '¿Aceptaría colaborar con el cumplimiento de las normas sociales en lugares públicos?', 'D', 'INTERES'),
  (59, '¿Cree que sus ideas son importantes y hace lo posible para ponerlas en práctica?', 'I', 'APTITUD'),
  (60, '¿Cuando, en la casa, se descompone un artefacto, Ud. se dispone prontamente a repararlo?', 'I', 'INTERES'),
  (61, '¿Formaría parte de un equipo de trabajo orientado a la preservación de la flora y de la fauna?', 'E', 'INTERES'),
  (62, '¿Tiene por costumbre leer revistas relacionadas con los últimos avances científicos y tecnológicos en el área de la salud?', 'S', 'INTERES'),
  (63, '¿Le parece importante y necesario preservar las raíces culturales de nuestro país?', 'H', 'APTITUD'),
  (64, '¿Le gustaría realizar una investigación que contribuyera a hacer más justa la distribución de la riqueza?', 'C', 'INTERES'),
  (65, '¿Le gustaría realizar tareas de mantenimiento y conservación de un barco como, por ejemplo, pintura y conservación del casco, mantenimiento de los motores, etc.?', 'D', 'INTERES'),
  (66, '¿Cree que el país debe poseer la más alta tecnología armamentista a cualquier precio?', 'D', 'APTITUD'),
  (67, '¿La libertad y la justicia son valores fundamentales en la vida?', 'H', 'INTERES'),
  (68, '¿Aceptaría hacer práctica rentada en una industria de productos alimenticios en el sector de control de calidad?', 'E', 'INTERES'),
  (69, '¿Considera que la salud pública debe ser prioritaria, gratuita y eficiente para todos?', 'S', 'APTITUD'),
  (70, '¿Le interesaría investigar sobre una nueva vacuna?', 'S', 'INTERES'),
  (71, '¿Le gusta ocupar el rol de coordinador/a en un equipo de trabajo?', 'C', 'INTERES'),
  (72, '¿En una discusión entre amigos(as), se ofrece como mediador/a?', 'H', 'APTITUD'),
  (73, '¿Está de acuerdo con la formación de un cuerpo de soldados profesionales?', 'D', 'INTERES'),
  (74, '¿Lucharía por una causa justa hasta las últimas consecuencias?', 'H', 'INTERES'),
  (75, '¿Le gustaría investigar científicamente sobre cultivos agrícolas?', 'I', 'INTERES'),
  (76, '¿Haría un nuevo diseño de una prenda pasada de moda, ante una reunión imprevista?', 'A', 'APTITUD'),
  (77, '¿Visitaría un observatorio astronómico para conocerlo en acción?', 'E', 'INTERES'),
  (78, '¿Le gustaría dirigir el área de importación/exportación de una empresa?', 'C', 'INTERES'),
  (79, '¿Se siente inhibido/a al entrar en un lugar desconocido con gente que no conoce?', 'E', 'APTITUD'),
  (80, '¿Le gratificaría trabajar con niños?', 'H', 'INTERES'),
  (81, '¿Haría un logotipo para un afiche de una campaña de prevención del SIDA?', 'A', 'INTERES'),
  (82, '¿Dirigiría un grupo de teatro?', 'A', 'APTITUD'),
  (83, '¿Enviaría su Currículum a una empresa automotriz que solicita un gerente para el área de producción?', 'I', 'INTERES'),
  (84, '¿Participaría de un grupo internacional de defensa de algo justo y benéfico para la humanidad?', 'D', 'INTERES'),
  (85, '¿Se costearía sus estudios trabajando?', 'C', 'INTERES'),
  (86, '¿Suele defender las llamadas «causas perdidas»?', 'H', 'APTITUD'),
  (87, '¿Ante una emergencia, participaría brindando su ayuda?', 'S', 'INTERES'),
  (88, '¿Sabe el significado de las siglas ADN y ARN?', 'E', 'INTERES'),
  (89, '¿Elegiría una carrera universitaria cuyo instrumento de trabajo fuera la utilización de un idioma extranjero?', 'H', 'INTERES'),
  (90, '¿Trabajar con objetos le resulta más gratificante que trabajar con personas?', 'I', 'APTITUD'),
  (91, '¿Le gustaría ser el asesor contable de una empresa?', 'C', 'INTERES'),
  (92, '¿Ante un llamado solidario, se ofrecería para cuidar a un enfermo?', 'S', 'INTERES'),
  (93, '¿Se siente atraído/a por la investigación de los misterios del universo como, por ejemplo, la capa de ozono?', 'E', 'INTERES'),
  (94, '¿El trabajo individual le resulta más rápido y efectivo que el trabajo grupal?', 'E', 'APTITUD'),
  (95, '¿Dedicaría parte de su tiempo a ayudar a los habitantes de zonas carenciadas?', 'H', 'INTERES'),
  (96, '¿Cuando decora un ambiente, tiene en cuenta la combinación de los colores, el estilo preferido, etc.?', 'A', 'INTERES'),
  (97, '¿Le gustaría trabajar como profesional dirigiendo la construcción de una empresa hidroeléctrica?', 'I', 'INTERES'),
  (98, '¿Sabe el significado de la sigla PBI?', 'C', 'INTERES')
) AS q(numero, texto, categoria, dimension);

COMMIT;
